export interface MoneyGramCorridor {
  code: string; // ISO 2-letter
  alpha3: string; // ISO 3-letter (matches MoneyGram portal tags like "Nigeria NGA")
  country: string;
  currency: string;
  symbol: string;
  flag: string;
  region: 'Africa' | 'Americas' | 'Europe' | 'Asia-Pacific' | 'Middle East';
  cashOutEnabled: boolean;
  cashInEnabled: boolean;
  minAmountUsd: number;
  maxAmountUsd: number;
  estimatedRate: number; // Estimated local currency per 1 USDC
}

/**
 * Official MoneyGram Global Product Policy Corridors
 * Derived directly from active MoneyGram Partner Policy:
 * - Cash-out: $5.00 - $2,500.00 USD across 167 global countries
 * - Cash-in: $5.00 - $950.00 USD across 27 enabled countries
 * - Excluded US States: Alaska (US-AK), Hawaii (US-HI), Louisiana (US-LA)
 */
export const MONEYGRAM_GLOBAL_CORRIDORS: MoneyGramCorridor[] = [
  {
    code: "AL",
    alpha3: "ALB",
    country: 'Albania',
    currency: 'ALL',
    symbol: 'Lek',
    flag: '🇦🇱',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 94.2,
  },
  {
    code: "AO",
    alpha3: "AGO",
    country: 'Angola',
    currency: 'AOA',
    symbol: 'Kz',
    flag: '🇦🇴',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 915,
  },
  {
    code: "AI",
    alpha3: "AIA",
    country: 'Anguilla',
    currency: 'XCD',
    symbol: '$',
    flag: '🇦🇮',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "AG",
    alpha3: "ATG",
    country: 'Antigua & Barbuda',
    currency: 'XCD',
    symbol: '$',
    flag: '🇦🇬',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "AR",
    alpha3: "ARG",
    country: 'Argentina',
    currency: 'ARS',
    symbol: '$',
    flag: '🇦🇷',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1040,
  },
  {
    code: "AM",
    alpha3: "ARM",
    country: 'Armenia',
    currency: 'AMD',
    symbol: '֏',
    flag: '🇦🇲',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 395,
  },
  {
    code: "AW",
    alpha3: "ABM",
    country: 'Aruba',
    currency: 'AWG',
    symbol: 'ƒ',
    flag: '🇦🇼',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.8,
  },
  {
    code: "AU",
    alpha3: "AUS",
    country: 'Australia',
    currency: 'AUD',
    symbol: '$',
    flag: '🇦🇺',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.54,
  },
  {
    code: "AT",
    alpha3: "AUT",
    country: 'Austria',
    currency: 'EUR',
    symbol: '€',
    flag: '🇦🇹',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "BS",
    alpha3: "BHS",
    country: 'Bahamas',
    currency: 'BSD',
    symbol: '$',
    flag: '🇧🇸',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "BH",
    alpha3: "BHR",
    country: 'Bahrain',
    currency: 'BHD',
    symbol: '.د.ب',
    flag: '🇧🇭',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.38,
  },
  {
    code: "BB",
    alpha3: "BRB",
    country: 'Barbados',
    currency: 'BBD',
    symbol: '$',
    flag: '🇧🇧',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2,
  },
  {
    code: "BY",
    alpha3: "BLR",
    country: 'Belarus',
    currency: 'BYN',
    symbol: 'Br',
    flag: '🇧🇾',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3.28,
  },
  {
    code: "BE",
    alpha3: "BEL",
    country: 'Belgium',
    currency: 'EUR',
    symbol: '€',
    flag: '🇧🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "BZ",
    alpha3: "BLZ",
    country: 'Belize',
    currency: 'BZD',
    symbol: '$',
    flag: '🇧🇿',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2,
  },
  {
    code: "BJ",
    alpha3: "BEN",
    country: 'Benin',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇧🇯',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "BM",
    alpha3: "BMU",
    country: 'Bermuda',
    currency: 'BMD',
    symbol: '$',
    flag: '🇧🇲',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "BT",
    alpha3: "BTN",
    country: 'Bhutan',
    currency: 'BTN',
    symbol: 'Nu.',
    flag: '🇧🇹',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 84.5,
  },
  {
    code: "BO",
    alpha3: "BOL",
    country: 'Bolivia',
    currency: 'BOB',
    symbol: 'Bs.',
    flag: '🇧🇴',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 6.9,
  },
  {
    code: "BA",
    alpha3: "BIH",
    country: 'Bosnia & Herzegovina',
    currency: 'BAM',
    symbol: 'KM',
    flag: '🇧🇦',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.8,
  },
  {
    code: "BW",
    alpha3: "BWA",
    country: 'Botswana',
    currency: 'BWP',
    symbol: 'P',
    flag: '🇧🇼',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 13.6,
  },
  {
    code: "BR",
    alpha3: "BRA",
    country: 'Brazil',
    currency: 'BRL',
    symbol: 'R$',
    flag: '🇧🇷',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 5.75,
  },
  {
    code: "VG",
    alpha3: "VGB",
    country: 'British Virgin Islands',
    currency: 'USD',
    symbol: '$',
    flag: '🇻🇬',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "BN",
    alpha3: "BRN",
    country: 'Brunei',
    currency: 'BND',
    symbol: '$',
    flag: '🇧🇳',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.34,
  },
  {
    code: "BG",
    alpha3: "BGR",
    country: 'Bulgaria',
    currency: 'BGN',
    symbol: 'лв',
    flag: '🇧🇬',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.8,
  },
  {
    code: "BF",
    alpha3: "BFA",
    country: 'Burkina Faso',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇧🇫',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "KH",
    alpha3: "KHM",
    country: 'Cambodia',
    currency: 'KHR',
    symbol: '៛',
    flag: '🇰🇭',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4050,
  },
  {
    code: "CM",
    alpha3: "CMR",
    country: 'Cameroon',
    currency: 'XAF',
    symbol: 'FCFA',
    flag: '🇨🇲',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "CA",
    alpha3: "CAN",
    country: 'Canada',
    currency: 'CAD',
    symbol: '$',
    flag: '🇨🇦',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.38,
  },
  {
    code: "CV",
    alpha3: "CPV",
    country: 'Cape Verde',
    currency: 'CVE',
    symbol: '$',
    flag: '🇨🇻',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 101.5,
  },
  {
    code: "KY",
    alpha3: "CYM",
    country: 'Cayman Islands',
    currency: 'KYD',
    symbol: '$',
    flag: '🇰🇾',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.83,
  },
  {
    code: "CF",
    alpha3: "CAF",
    country: 'Central African Republic',
    currency: 'XAF',
    symbol: 'FCFA',
    flag: '🇨🇫',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "TD",
    alpha3: "TCD",
    country: 'Chad',
    currency: 'XAF',
    symbol: 'FCFA',
    flag: '🇹🇩',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "CL",
    alpha3: "CHL",
    country: 'Chile',
    currency: 'CLP',
    symbol: '$',
    flag: '🇨🇱',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 940,
  },
  {
    code: "CO",
    alpha3: "COL",
    country: 'Colombia',
    currency: 'COP',
    symbol: '$',
    flag: '🇨🇴',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4180,
  },
  {
    code: "KM",
    alpha3: "COM",
    country: 'Comoros',
    currency: 'KMF',
    symbol: 'CF',
    flag: '🇰🇲',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 452,
  },
  {
    code: "CG",
    alpha3: "COG",
    country: 'Congo - Brazzaville',
    currency: 'XAF',
    symbol: 'FCFA',
    flag: '🇨🇬',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "CD",
    alpha3: "COD",
    country: 'Congo - Kinshasa',
    currency: 'CDF',
    symbol: 'FC',
    flag: '🇨🇩',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2850,
  },
  {
    code: "CR",
    alpha3: "CRI",
    country: 'Costa Rica',
    currency: 'CRC',
    symbol: '₡',
    flag: '🇨🇷',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 512,
  },
  {
    code: "CI",
    alpha3: "CIV",
    country: 'Côte d\'Ivoire',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇨🇮',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "CW",
    alpha3: "CUW",
    country: 'Curaçao',
    currency: 'ANG',
    symbol: 'ƒ',
    flag: '🇨🇼',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.8,
  },
  {
    code: "CY",
    alpha3: "CYP",
    country: 'Cyprus',
    currency: 'EUR',
    symbol: '€',
    flag: '🇨🇾',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "CZ",
    alpha3: "CZE",
    country: 'Czechia',
    currency: 'CZK',
    symbol: 'Kč',
    flag: '🇨🇿',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 23.4,
  },
  {
    code: "DK",
    alpha3: "DNK",
    country: 'Denmark',
    currency: 'DKK',
    symbol: 'kr',
    flag: '🇩🇰',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 6.9,
  },
  {
    code: "DJ",
    alpha3: "DJI",
    country: 'Djibouti',
    currency: 'DJF',
    symbol: 'Fdj',
    flag: '🇩🇯',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 178,
  },
  {
    code: "DM",
    alpha3: "DMA",
    country: 'Dominica',
    currency: 'XCD',
    symbol: '$',
    flag: '🇩🇲',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "DO",
    alpha3: "DOM",
    country: 'Dominican Republic',
    currency: 'DOP',
    symbol: 'RD$',
    flag: '🇩🇴',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 60.1,
  },
  {
    code: "EC",
    alpha3: "ECU",
    country: 'Ecuador',
    currency: 'USD',
    symbol: '$',
    flag: '🇪🇨',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "SV",
    alpha3: "SLV",
    country: 'El Salvador',
    currency: 'USD',
    symbol: '$',
    flag: '🇸🇻',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "EE",
    alpha3: "EST",
    country: 'Estonia',
    currency: 'EUR',
    symbol: '€',
    flag: '🇪🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "SZ",
    alpha3: "SWZ",
    country: 'Eswatini',
    currency: 'SZL',
    symbol: 'E',
    flag: '🇸🇿',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 17.8,
  },
  {
    code: "ET",
    alpha3: "ETH",
    country: 'Ethiopia',
    currency: 'ETB',
    symbol: 'Br',
    flag: '🇪🇹',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 125,
  },
  {
    code: "FJ",
    alpha3: "FJI",
    country: 'Fiji',
    currency: 'FJD',
    symbol: '$',
    flag: '🇫🇯',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.25,
  },
  {
    code: "FR",
    alpha3: "FRA",
    country: 'France',
    currency: 'EUR',
    symbol: '€',
    flag: '🇫🇷',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "GF",
    alpha3: "GUF",
    country: 'French Guiana',
    currency: 'EUR',
    symbol: '€',
    flag: '🇬🇫',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "GA",
    alpha3: "GAB",
    country: 'Gabon',
    currency: 'XAF',
    symbol: 'FCFA',
    flag: '🇬🇦',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "GM",
    alpha3: "GMB",
    country: 'Gambia',
    currency: 'GMD',
    symbol: 'D',
    flag: '🇬🇲',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 70.5,
  },
  {
    code: "GE",
    alpha3: "GEO",
    country: 'Georgia',
    currency: 'GEL',
    symbol: '₾',
    flag: '🇬🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.72,
  },
  {
    code: "DE",
    alpha3: "DEU",
    country: 'Germany',
    currency: 'EUR',
    symbol: '€',
    flag: '🇩🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "GH",
    alpha3: "GHA",
    country: 'Ghana',
    currency: 'GHS',
    symbol: 'GH₵',
    flag: '🇬🇭',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 15.6,
  },
  {
    code: "GI",
    alpha3: "GIB",
    country: 'Gibraltar',
    currency: 'GIP',
    symbol: '£',
    flag: '🇬🇮',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.77,
  },
  {
    code: "GR",
    alpha3: "GRC",
    country: 'Greece',
    currency: 'EUR',
    symbol: '€',
    flag: '🇬🇷',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "GD",
    alpha3: "GRD",
    country: 'Grenada',
    currency: 'XCD',
    symbol: '$',
    flag: '🇬🇩',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "GP",
    alpha3: "GLP",
    country: 'Guadeloupe',
    currency: 'EUR',
    symbol: '€',
    flag: '🇬🇵',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "GT",
    alpha3: "GTM",
    country: 'Guatemala',
    currency: 'GTQ',
    symbol: 'Q',
    flag: '🇬🇹',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 7.75,
  },
  {
    code: "GW",
    alpha3: "GNB",
    country: 'Guinea-Bissau',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇬🇼',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "GY",
    alpha3: "GUY",
    country: 'Guyana',
    currency: 'GYD',
    symbol: '$',
    flag: '🇬🇾',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 209,
  },
  {
    code: "HN",
    alpha3: "HND",
    country: 'Honduras',
    currency: 'HNL',
    symbol: 'L',
    flag: '🇭🇳',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 24.8,
  },
  {
    code: "HK",
    alpha3: "HKG",
    country: 'Hong Kong',
    currency: 'HKD',
    symbol: 'HK$',
    flag: '🇭🇰',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 7.78,
  },
  {
    code: "HU",
    alpha3: "HUN",
    country: 'Hungary',
    currency: 'HUF',
    symbol: 'Ft',
    flag: '🇭🇺',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 368,
  },
  {
    code: "IN",
    alpha3: "IND",
    country: 'India',
    currency: 'INR',
    symbol: '₹',
    flag: '🇮🇳',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 85.2,
  },
  {
    code: "ID",
    alpha3: "IDN",
    country: 'Indonesia',
    currency: 'IDR',
    symbol: 'Rp',
    flag: '🇮🇩',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 15700,
  },
  {
    code: "IE",
    alpha3: "IRL",
    country: 'Ireland',
    currency: 'EUR',
    symbol: '€',
    flag: '🇮🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "IL",
    alpha3: "ISR",
    country: 'Israel',
    currency: 'ILS',
    symbol: '₪',
    flag: '🇮🇱',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3.65,
  },
  {
    code: "IT",
    alpha3: "ITA",
    country: 'Italy',
    currency: 'EUR',
    symbol: '€',
    flag: '🇮🇹',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "JM",
    alpha3: "JAM",
    country: 'Jamaica',
    currency: 'JMD',
    symbol: 'J$',
    flag: '🇯🇲',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 156,
  },
  {
    code: "JP",
    alpha3: "JPN",
    country: 'Japan',
    currency: 'JPY',
    symbol: '¥',
    flag: '🇯🇵',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 152,
  },
  {
    code: "JO",
    alpha3: "JOR",
    country: 'Jordan',
    currency: 'JOD',
    symbol: 'JD',
    flag: '🇯🇴',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.71,
  },
  {
    code: "KZ",
    alpha3: "KAZ",
    country: 'Kazakhstan',
    currency: 'KZT',
    symbol: '₸',
    flag: '🇰🇿',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 495,
  },
  {
    code: "KE",
    alpha3: "KEN",
    country: 'Kenya',
    currency: 'KES',
    symbol: 'KSh',
    flag: '🇰🇪',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 129.8,
  },
  {
    code: "XK",
    alpha3: "XKX",
    country: 'Kosovo',
    currency: 'EUR',
    symbol: '€',
    flag: '🇽🇰',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "KG",
    alpha3: "KGZ",
    country: 'Kyrgyzstan',
    currency: 'KGS',
    symbol: 'сом',
    flag: '🇰🇬',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 86.5,
  },
  {
    code: "LA",
    alpha3: "LAO",
    country: 'Laos',
    currency: 'LAK',
    symbol: '₭',
    flag: '🇱🇦',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 21800,
  },
  {
    code: "LV",
    alpha3: "LVA",
    country: 'Latvia',
    currency: 'EUR',
    symbol: '€',
    flag: '🇱🇻',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "LB",
    alpha3: "LBN",
    country: 'Lebanon',
    currency: 'LBP',
    symbol: 'L£',
    flag: '🇱🇧',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 89500,
  },
  {
    code: "LR",
    alpha3: "LBR",
    country: 'Liberia',
    currency: 'LRD',
    symbol: '$',
    flag: '🇱🇷',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 198,
  },
  {
    code: "LY",
    alpha3: "LBY",
    country: 'Libya',
    currency: 'LYD',
    symbol: 'LD',
    flag: '🇱🇾',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4.85,
  },
  {
    code: "LU",
    alpha3: "LUX",
    country: 'Luxembourg',
    currency: 'EUR',
    symbol: '€',
    flag: '🇱🇺',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "MG",
    alpha3: "MDG",
    country: 'Madagascar',
    currency: 'MGA',
    symbol: 'Ar',
    flag: '🇲🇬',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4600,
  },
  {
    code: "MW",
    alpha3: "MWI",
    country: 'Malawi',
    currency: 'MWK',
    symbol: 'MK',
    flag: '🇲🇼',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1735,
  },
  {
    code: "MY",
    alpha3: "MYS",
    country: 'Malaysia',
    currency: 'MYR',
    symbol: 'RM',
    flag: '🇲🇾',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4.38,
  },
  {
    code: "MV",
    alpha3: "MDV",
    country: 'Maldives',
    currency: 'MVR',
    symbol: 'Rf',
    flag: '🇲🇻',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 15.4,
  },
  {
    code: "ML",
    alpha3: "MLI",
    country: 'Mali',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇲🇱',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "MT",
    alpha3: "MLT",
    country: 'Malta',
    currency: 'EUR',
    symbol: '€',
    flag: '🇲🇹',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "MH",
    alpha3: "MHL",
    country: 'Marshall Islands',
    currency: 'USD',
    symbol: '$',
    flag: '🇲🇭',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "MQ",
    alpha3: "MTQ",
    country: 'Martinique',
    currency: 'EUR',
    symbol: '€',
    flag: '🇲🇶',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "MR",
    alpha3: "MRT",
    country: 'Mauritania',
    currency: 'MRU',
    symbol: 'UM',
    flag: '🇲🇷',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 39.8,
  },
  {
    code: "MU",
    alpha3: "MUS",
    country: 'Mauritius',
    currency: 'MUR',
    symbol: '₨',
    flag: '🇲🇺',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 46.5,
  },
  {
    code: "YT",
    alpha3: "MYT",
    country: 'Mayotte',
    currency: 'EUR',
    symbol: '€',
    flag: '🇾🇹',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "MX",
    alpha3: "MEX",
    country: 'Mexico',
    currency: 'MXN',
    symbol: '$',
    flag: '🇲🇽',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 20.1,
  },
  {
    code: "FM",
    alpha3: "FSM",
    country: 'Micronesia',
    currency: 'USD',
    symbol: '$',
    flag: '🇫🇲',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "MD",
    alpha3: "MDA",
    country: 'Moldova',
    currency: 'MDL',
    symbol: 'L',
    flag: '🇲🇩',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 18,
  },
  {
    code: "MN",
    alpha3: "MNG",
    country: 'Mongolia',
    currency: 'MNT',
    symbol: '₮',
    flag: '🇲🇳',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3420,
  },
  {
    code: "ME",
    alpha3: "MNE",
    country: 'Montenegro',
    currency: 'EUR',
    symbol: '€',
    flag: '🇲🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "MS",
    alpha3: "MSR",
    country: 'Montserrat',
    currency: 'XCD',
    symbol: '$',
    flag: '🇲🇸',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "MZ",
    alpha3: "MOZ",
    country: 'Mozambique',
    currency: 'MZN',
    symbol: 'MT',
    flag: '🇲🇿',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 63.8,
  },
  {
    code: "MM",
    alpha3: "MMR",
    country: 'Myanmar (Burma)',
    currency: 'MMK',
    symbol: 'K',
    flag: '🇲🇲',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2100,
  },
  {
    code: "NA",
    alpha3: "NAM",
    country: 'Namibia',
    currency: 'NAD',
    symbol: '$',
    flag: '🇳🇦',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 17.8,
  },
  {
    code: "NL",
    alpha3: "NLD",
    country: 'Netherlands',
    currency: 'EUR',
    symbol: '€',
    flag: '🇳🇱',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "NZ",
    alpha3: "NZL",
    country: 'New Zealand',
    currency: 'NZD',
    symbol: '$',
    flag: '🇳🇿',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.68,
  },
  {
    code: "NI",
    alpha3: "NIC",
    country: 'Nicaragua',
    currency: 'NIO',
    symbol: 'C$',
    flag: '🇳🇮',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 36.8,
  },
  {
    code: "NE",
    alpha3: "NER",
    country: 'Niger',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇳🇪',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "NG",
    alpha3: "NGA",
    country: 'Nigeria',
    currency: 'NGN',
    symbol: '₦',
    flag: '🇳🇬',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1620,
  },
  {
    code: "MK",
    alpha3: "MKD",
    country: 'North Macedonia',
    currency: 'MKD',
    symbol: 'ден',
    flag: '🇲🇰',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 56.5,
  },
  {
    code: "NO",
    alpha3: "NOR",
    country: 'Norway',
    currency: 'NOK',
    symbol: 'kr',
    flag: '🇳🇴',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 10.9,
  },
  {
    code: "OM",
    alpha3: "OMN",
    country: 'Oman',
    currency: 'OMR',
    symbol: 'ر.ع.',
    flag: '🇴🇲',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.38,
  },
  {
    code: "PS",
    alpha3: "PSE",
    country: 'Palestine',
    currency: 'ILS',
    symbol: '₪',
    flag: '🇵🇸',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3.65,
  },
  {
    code: "PY",
    alpha3: "PRY",
    country: 'Paraguay',
    currency: 'PYG',
    symbol: '₲',
    flag: '🇵🇾',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 7750,
  },
  {
    code: "PE",
    alpha3: "PER",
    country: 'Peru',
    currency: 'PEN',
    symbol: 'S/.',
    flag: '🇵🇪',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3.77,
  },
  {
    code: "PH",
    alpha3: "PHL",
    country: 'Philippines',
    currency: 'PHP',
    symbol: '₱',
    flag: '🇵🇭',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 58.4,
  },
  {
    code: "PL",
    alpha3: "POL",
    country: 'Poland',
    currency: 'PLN',
    symbol: 'zł',
    flag: '🇵🇱',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4.02,
  },
  {
    code: "PT",
    alpha3: "PRT",
    country: 'Portugal',
    currency: 'EUR',
    symbol: '€',
    flag: '🇵🇹',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "PR",
    alpha3: "PRI",
    country: 'Puerto Rico',
    currency: 'USD',
    symbol: '$',
    flag: '🇵🇷',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "RE",
    alpha3: "REU",
    country: 'Réunion',
    currency: 'EUR',
    symbol: '€',
    flag: '🇷🇪',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "RO",
    alpha3: "ROU",
    country: 'Romania',
    currency: 'RON',
    symbol: 'lei',
    flag: '🇷🇴',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 4.58,
  },
  {
    code: "RW",
    alpha3: "RWA",
    country: 'Rwanda',
    currency: 'RWF',
    symbol: 'FRw',
    flag: '🇷🇼',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1380,
  },
  {
    code: "WS",
    alpha3: "WSM",
    country: 'Samoa',
    currency: 'WST',
    symbol: 'WS$',
    flag: '🇼🇸',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.76,
  },
  {
    code: "ST",
    alpha3: "STP",
    country: 'São Tomé & Príncipe',
    currency: 'STN',
    symbol: 'Db',
    flag: '🇸🇹',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 22.8,
  },
  {
    code: "SA",
    alpha3: "SAU",
    country: 'Saudi Arabia',
    currency: 'SAR',
    symbol: '﷼',
    flag: '🇸🇦',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3.75,
  },
  {
    code: "SN",
    alpha3: "SEN",
    country: 'Senegal',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇸🇳',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "RS",
    alpha3: "SRB",
    country: 'Serbia',
    currency: 'RSD',
    symbol: 'дин',
    flag: '🇷🇸',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 108,
  },
  {
    code: "SC",
    alpha3: "SYC",
    country: 'Seychelles',
    currency: 'SCR',
    symbol: 'SR',
    flag: '🇸🇨',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 14.2,
  },
  {
    code: "SL",
    alpha3: "SLE",
    country: 'Sierra Leone',
    currency: 'SLE',
    symbol: 'Le',
    flag: '🇸🇱',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 22.8,
  },
  {
    code: "SG",
    alpha3: "SGP",
    country: 'Singapore',
    currency: 'SGD',
    symbol: '$',
    flag: '🇸🇬',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.33,
  },
  {
    code: "SX",
    alpha3: "SXM",
    country: 'Sint Maarten',
    currency: 'ANG',
    symbol: 'ƒ',
    flag: '🇸🇽',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.8,
  },
  {
    code: "SB",
    alpha3: "SLB",
    country: 'Solomon Islands',
    currency: 'SBD',
    symbol: '$',
    flag: '🇸🇧',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 8.45,
  },
  {
    code: "ZA",
    alpha3: "ZAF",
    country: 'South Africa',
    currency: 'ZAR',
    symbol: 'R',
    flag: '🇿🇦',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 17.8,
  },
  {
    code: "KR",
    alpha3: "KOR",
    country: 'South Korea',
    currency: 'KRW',
    symbol: '₩',
    flag: '🇰🇷',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1385,
  },
  {
    code: "SS",
    alpha3: "SSD",
    country: 'South Sudan',
    currency: 'SSP',
    symbol: '£',
    flag: '🇸🇸',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 130,
  },
  {
    code: "ES",
    alpha3: "ESP",
    country: 'Spain',
    currency: 'EUR',
    symbol: '€',
    flag: '🇪🇸',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "LK",
    alpha3: "LKA",
    country: 'Sri Lanka',
    currency: 'LKR',
    symbol: 'Rs',
    flag: '🇱🇰',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 295,
  },
  {
    code: "KN",
    alpha3: "KNA",
    country: 'St. Kitts & Nevis',
    currency: 'XCD',
    symbol: '$',
    flag: '🇰🇳',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "LC",
    alpha3: "LCA",
    country: 'St. Lucia',
    currency: 'XCD',
    symbol: '$',
    flag: '🇱🇨',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "MF",
    alpha3: "MAF",
    country: 'St. Martin',
    currency: 'EUR',
    symbol: '€',
    flag: '🇲🇫',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.92,
  },
  {
    code: "VC",
    alpha3: "VCT",
    country: 'St. Vincent & Grenadines',
    currency: 'XCD',
    symbol: '$',
    flag: '🇻🇨',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.7,
  },
  {
    code: "SR",
    alpha3: "SUR",
    country: 'Suriname',
    currency: 'SRD',
    symbol: '$',
    flag: '🇸🇷',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 35.2,
  },
  {
    code: "SE",
    alpha3: "SWE",
    country: 'Sweden',
    currency: 'SEK',
    symbol: 'kr',
    flag: '🇸🇪',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 10.6,
  },
  {
    code: "CH",
    alpha3: "CHE",
    country: 'Switzerland',
    currency: 'CHF',
    symbol: 'CHF',
    flag: '🇨🇭',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 0.87,
  },
  {
    code: "TZ",
    alpha3: "TZA",
    country: 'Tanzania',
    currency: 'TZS',
    symbol: 'TSh',
    flag: '🇹🇿',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2650,
  },
  {
    code: "TH",
    alpha3: "THA",
    country: 'Thailand',
    currency: 'THB',
    symbol: '฿',
    flag: '🇹🇭',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 34.2,
  },
  {
    code: "TL",
    alpha3: "TLS",
    country: 'Timor-Leste',
    currency: 'USD',
    symbol: '$',
    flag: '🇹🇱',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "TG",
    alpha3: "TGO",
    country: 'Togo',
    currency: 'XOF',
    symbol: 'CFA',
    flag: '🇹🇬',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 605,
  },
  {
    code: "TO",
    alpha3: "TON",
    country: 'Tonga',
    currency: 'TOP',
    symbol: 'T$',
    flag: '🇹🇴',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 2.38,
  },
  {
    code: "TT",
    alpha3: "TTO",
    country: 'Trinidad & Tobago',
    currency: 'TTD',
    symbol: 'TT$',
    flag: '🇹🇹',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 6.78,
  },
  {
    code: "TC",
    alpha3: "TCA",
    country: 'Turks & Caicos Islands',
    currency: 'USD',
    symbol: '$',
    flag: '🇹🇨',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "TV",
    alpha3: "TUV",
    country: 'Tuvalu',
    currency: 'AUD',
    symbol: '$',
    flag: '🇹🇻',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1.54,
  },
  {
    code: "VI",
    alpha3: "VIR",
    country: 'U.S. Virgin Islands',
    currency: 'USD',
    symbol: '$',
    flag: '🇻🇮',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "UG",
    alpha3: "UGA",
    country: 'Uganda',
    currency: 'UGX',
    symbol: 'USh',
    flag: '🇺🇬',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3720,
  },
  {
    code: "UA",
    alpha3: "UKR",
    country: 'Ukraine',
    currency: 'UAH',
    symbol: '₴',
    flag: '🇺🇦',
    region: 'Europe',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 41.5,
  },
  {
    code: "AE",
    alpha3: "ARE",
    country: 'United Arab Emirates',
    currency: 'AED',
    symbol: 'د.إ',
    flag: '🇦🇪',
    region: 'Middle East',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 3.67,
  },
  {
    code: "US",
    alpha3: "USA",
    country: 'United States',
    currency: 'USD',
    symbol: '$',
    flag: '🇺🇸',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 1,
  },
  {
    code: "UY",
    alpha3: "URY",
    country: 'Uruguay',
    currency: 'UYU',
    symbol: '$U',
    flag: '🇺🇾',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 42.5,
  },
  {
    code: "UZ",
    alpha3: "UZB",
    country: 'Uzbekistan',
    currency: 'UZS',
    symbol: 'so\'m',
    flag: '🇺🇿',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 12800,
  },
  {
    code: "VU",
    alpha3: "VUT",
    country: 'Vanuatu',
    currency: 'VUV',
    symbol: 'VT',
    flag: '🇻🇺',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 120,
  },
  {
    code: "VE",
    alpha3: "VEN",
    country: 'Venezuela',
    currency: 'VES',
    symbol: 'Bs.',
    flag: '🇻🇪',
    region: 'Americas',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 48.5,
  },
  {
    code: "VN",
    alpha3: "VNM",
    country: 'Vietnam',
    currency: 'VND',
    symbol: '₫',
    flag: '🇻🇳',
    region: 'Asia-Pacific',
    cashOutEnabled: true,
    cashInEnabled: false,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 25400,
  },
  {
    code: "ZM",
    alpha3: "ZMB",
    country: 'Zambia',
    currency: 'ZMW',
    symbol: 'ZK',
    flag: '🇿🇲',
    region: 'Africa',
    cashOutEnabled: true,
    cashInEnabled: true,
    minAmountUsd: 5,
    maxAmountUsd: 2500,
    estimatedRate: 27.2,
  },
];

/**
 * Top priority featured corridors (Africa & high-volume remittance corridors)
 */
export const FEATURED_CORRIDOR_CODES = [
  'NG', 'KE', 'GH', 'UG', 'ZA', 'RW', 'US', 'CO', 'PH', 'AR', 'BR', 'CA', 'DE', 'AE', 'TZ', 'ZM'
];

/**
 * Official MoneyGram Integration Policy Constants
 * Sourced directly from MoneyGram Integration Policy:
 * - Cash-in: $5.00 – $950.00 USD across 27 enabled countries
 * - Cash-out: $5.00 – $2,500.00 USD across 167 enabled countries
 * - Excluded US States: Alaska (US-AK), Hawaii (US-HI), Louisiana (US-LA)
 */
export const MONEYGRAM_POLICY = {
  cashIn: {
    enabled: true,
    minAmountUsd: 5.0,
    maxAmountUsd: 950.0,
    allowedCountriesCount: 27,
  },
  cashOut: {
    enabled: true,
    minAmountUsd: 5.0,
    maxAmountUsd: 2500.0,
    allowedCountriesCount: 167,
  },
  excludedUsStates: [
    { code: "US-AK", name: "Alaska" },
    { code: "US-HI", name: "Hawaii" },
    { code: "US-LA", name: "Louisiana" },
  ],
  excludedUsStateCodes: ["US-AK", "US-HI", "US-LA"],
} as const;

export const MONEYGRAM_CASH_IN_ALPHA3 = new Set<string>([
  "AGO", "ARG", "AUS", "BHR", "BFA", "KHM", "CAN", "CPV", "CIV", "DNK",
  "GMB", "DEU", "GNB", "HUN", "IRL", "KEN", "MWI", "NOR", "OMN", "POL",
  "SAU", "SEN", "ZAF", "TZA", "UGA", "USA", "ZMB"
]);

export function isCashInAllowed(alpha3OrCode: string): boolean {
  const norm = (alpha3OrCode || "").trim().toUpperCase();
  if (MONEYGRAM_CASH_IN_ALPHA3.has(norm)) return true;
  const match = MONEYGRAM_GLOBAL_CORRIDORS.find((c) => c.code === norm);
  return match ? MONEYGRAM_CASH_IN_ALPHA3.has(match.alpha3) : false;
}

export function isCashOutAllowed(alpha3OrCode: string): boolean {
  const norm = (alpha3OrCode || "").trim().toUpperCase();
  const match = MONEYGRAM_GLOBAL_CORRIDORS.find((c) => c.code === norm || c.alpha3 === norm);
  return Boolean(match?.cashOutEnabled);
}

export function isUsStateExcluded(stateCode: string): boolean {
  return (MONEYGRAM_POLICY.excludedUsStateCodes as readonly string[]).includes((stateCode || "").toUpperCase());
}
