/**
 * Provision a PERSISTENT Base wallet for a real end-to-end test.
 *
 * Everything so far has been proven against empty wallets: construction,
 * signing and broadcast all reach on-chain execution and stop at "transfer
 * amount exceeds balance". That is the correct failure for an empty wallet,
 * but it means the last mile - funds actually moving - has never run.
 *
 * This creates a wallet that SURVIVES between runs, so it can be funded once
 * and reused. Two things make that work:
 *
 *   - a fixed userId, so Privy returns the same wallet rather than minting a
 *     new address every run (Privy does not deduplicate; only the idempotency
 *     key and the reuse lookup prevent that)
 *   - a fixed key quorum, written to .env.e2e, because additional signers are
 *     attached AT CREATION and cannot be added later - a wallet provisioned
 *     without one can never be delegated to
 *
 * Run: npm run base:e2e-setup
 */

import 'dotenv/config';
import fs from 'node:fs';
import path from 'node:path';
import { generateAuthorizationKeyPair } from '../src/wallets/provider/privy-authorization.js';

const APP_ID = process.env.PRIVY_APP_ID ?? '';
const APP_SECRET = process.env.PRIVY_APP_SECRET ?? '';
const BASE = 'https://api.privy.io/v1';

/** Fixed so the same wallet comes back on every run. */
const E2E_USER_ID = 'sivan_base_e2e_wallet';
const STATE_FILE = path.join(process.cwd(), '.env.e2e');

const headers = () => ({
  'Content-Type': 'application/json',
  Authorization: `Basic ${Buffer.from(`${APP_ID}:${APP_SECRET}`).toString('base64')}`,
  'privy-app-id': APP_ID,
});

async function main() {
  if (!APP_ID || !APP_SECRET) {
    console.error('\nPRIVY_APP_ID / PRIVY_APP_SECRET are not set.\n');
    process.exit(1);
  }

  // Reuse the existing quorum if this has been run before. Generating a new
  // one would produce a wallet the OLD key cannot sign for, and the old wallet
  // could never be delegated to the new key.
  let quorumId = process.env.E2E_KEY_QUORUM_ID ?? '';
  let privateKeyPem = process.env.E2E_AUTHORIZATION_PRIVATE_KEY ?? '';

  if (fs.existsSync(STATE_FILE)) {
    const existing = fs.readFileSync(STATE_FILE, 'utf8');
    quorumId = /E2E_KEY_QUORUM_ID=(.+)/.exec(existing)?.[1]?.trim() ?? quorumId;
    const pem = /E2E_AUTHORIZATION_PRIVATE_KEY_B64=(.+)/.exec(existing)?.[1]?.trim();
    if (pem) privateKeyPem = Buffer.from(pem, 'base64').toString('utf8');
    console.log('Reusing the signer from .env.e2e');
  }

  if (!quorumId || !privateKeyPem) {
    const keyPair = generateAuthorizationKeyPair();
    privateKeyPem = keyPair.privateKeyPem;

    const quorum: any = await (await fetch(`${BASE}/key_quorums`, {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({
        display_name: 'sivan-base-e2e',
        public_keys: [keyPair.publicKeySpki],
        authorization_threshold: 1,
      }),
    })).json();

    if (!quorum?.id) throw new Error(`Could not create key quorum: ${JSON.stringify(quorum)}`);
    quorumId = quorum.id;

    // Base64 so the PEM survives a .env file, where raw newlines break parsing.
    fs.writeFileSync(
      STATE_FILE,
      [
        '# Generated by npm run base:e2e-setup. NOT for production.',
        '# The private key here can move funds in the e2e wallet below.',
        `E2E_KEY_QUORUM_ID=${quorumId}`,
        `E2E_AUTHORIZATION_PRIVATE_KEY_B64=${Buffer.from(privateKeyPem).toString('base64')}`,
        '',
      ].join('\n'),
      { mode: 0o600 }
    );
    console.log(`Created a new signer, saved to ${STATE_FILE}`);
  }

  // One Privy user for the test wallet, found rather than recreated.
  const list: any = await (await fetch(`${BASE}/users?limit=100`, { headers: headers() })).json();
  let user = (list.data ?? []).find((candidate: any) =>
    (candidate.linked_accounts ?? []).some(
      (account: any) => account.type === 'custom_auth' && account.custom_user_id === E2E_USER_ID
    )
  );

  if (!user) {
    user = await (await fetch(`${BASE}/users`, {
      method: 'POST',
      headers: headers(),
      body: JSON.stringify({ linked_accounts: [{ type: 'custom_auth', custom_user_id: E2E_USER_ID }] }),
    })).json();
  }

  const existingWallet = (user.linked_accounts ?? []).find(
    (account: any) => account.type === 'wallet' && account.chain_type === 'ethereum'
  );

  let wallet: any;
  if (existingWallet?.id) {
    // Re-read it: user.linked_accounts carries NO additional_signers field, so
    // the projection cannot tell us whether this wallet is delegated.
    wallet = await (await fetch(`${BASE}/wallets/${existingWallet.id}`, { headers: headers() })).json();
  } else {
    wallet = await (await fetch(`${BASE}/wallets`, {
      method: 'POST',
      headers: { ...headers(), 'privy-idempotency-key': `sivan_wallet_${E2E_USER_ID}_ethereum` },
      body: JSON.stringify({
        chain_type: 'ethereum',
        owner: { user_id: user.id },
        additional_signers: [{ signer_id: quorumId }],
      }),
    })).json();
  }

  const signers = (wallet.additional_signers ?? []).map((s: any) => s.signer_id);
  const delegated = signers.includes(quorumId);

  console.log('\n' + '='.repeat(64));
  console.log('  FUND THIS ADDRESS ON BASE SEPOLIA');
  console.log('='.repeat(64));
  console.log(`\n  ${wallet.address}\n`);
  console.log('='.repeat(64));
  console.log(`  privy user   ${user.id}`);
  console.log(`  wallet id    ${wallet.id}`);
  console.log(`  signer       ${quorumId}`);
  console.log(`  delegated    ${delegated ? 'YES - Sivan can sign for it' : 'NO'}`);
  console.log('='.repeat(64));

  if (!delegated) {
    // Not recoverable: adding a signer later needs the OWNER's signature,
    // which Sivan does not have.
    console.log('\n  This wallet has no Sivan signer and can never gain one.');
    console.log('  Delete the Privy user and re-run to get a delegated wallet.\n');
  }

  console.log('\n  Send TEST USDC on BASE SEPOLIA, not mainnet, not ETH.');
  console.log('  USDC contract: 0x036CbD53842c5426634e7929541eC2318f3dCF7e');
  console.log('  Faucet:        https://faucet.circle.com  (select Base Sepolia)');
  console.log('  ~2 USDC is plenty. Gas is sponsored, so no ETH is needed.');
  console.log('\n  Then run: npm run base:e2e-transfer\n');
}

main().catch((error) => { console.error('\nthrew:', error); process.exit(1); });
